### ISSUE TITLE
How to write UDP?

### ISSUE THREAD

**Issue by ayanamist** [tidwall/evio#19]
#13 shows how to use `Wake` to write something, but comment of `Wake` says:

> Not available for UDP connections.

Like i receive a tcp connection, how can i write to another udp conn?

**Comment by tidwall** [comment]
Unfortunately evio is limited to incoming connections for UDP at this time.

**Comment by tidwall** [comment]
I'm closing this issue for now, but please feel free to reopen if needed.

**Comment by hay187** [comment]
Is this still the case?  Can evio handle in/out udp and tcp?  Do we still need to fire wake?  It seems a like a rather messy solution to simply writing to the socket?
