### ISSUE TITLE
typo (evio_other.go:32:9: undefined: servenet)

### ISSUE THREAD

**Issue by thesyncim** [tidwall/evio#22]
https://github.com/tidwall/evio/blob/e74aca3b5aba81ff5cc6409ebc561d3cc0ba75e0/evio_other.go#L32

stdserve !?

**Comment by tidwall** [comment]
Which OS are you running?

**Comment by thesyncim** [comment]
go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\joana\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\joana\go
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\joana\AppData\Local\Temp\go-build968448006=/tmp/go-build -gno-record-gcc-witches

**Comment by tidwall** [comment]
I just pushed the fix. Thanks for reporting the issue.
