### ISSUE TITLE
nginx vs evio benchmark

### ISSUE THREAD

**Issue by dalovar** [tidwall/evio#29]
Would love to see a performance benchmark between evio and nginx instead of go's native http/fashttp. Assuming evio is more performant than nginx, does evio have any native protection against DDoS attacks and similar attacks that more popular web servers protect against?

**Comment by tidwall** [comment]
Thanks for the suggestion. I will consider more benchmarks in the future.

Unfortunately, Evio has no built-in protection against DDoS attacks.
