### ISSUE TITLE
Writing to UDP

### ISSUE THREAD

**Issue by hay187** [tidwall/evio#36]
Is this still the case?

https://github.com/tidwall/evio/issues/19

**Comment by tidwall** [comment]
You can write to UDP when the `Data` event fires by returning bytes to the output.  Calling `Wake` will force a `Data` to fire and should allow for arbitrary writes to the UDP connection.

**Comment by hay187** [comment]
Thanks for the quick response :). Is this quite stable and ready for production?

**Comment by tidwall** [comment]
Evio is production ready. 
Yes, If you use multithreading then you should use locks for shared data.
