### ISSUE TITLE
how to register new connection to event loop?

### ISSUE THREAD

**Issue by devguo** [tidwall/evio#37]
Thanks for the cool library. 
My scenario is,  server A use evio, and A need connect to server B, mark the connection as C, how to register  C to the server A event loop?

**Comment by tidwall** [comment]
I'm sorry, but I don't fully understand what you mean. 

But, from the sounds of it, you want an evio server (A) to dial a non-evio server (C)? 

That's not possible with the current design because evio is only for receiving connections, not dialing.

**Comment by devguo** [comment]
Yes, it is what i mean, thanks for your reply.
