### ISSUE TITLE
Why include iris in the bench?

### ISSUE THREAD

**Issue by uschen** [tidwall/evio#5]

**Comment by tidwall** [comment]
They claimed to be the fastest and I wanted to a simple benchmark to compare against.

**Comment by hiyali** [comment]
@tidwall Iris's author is not good i guess, just look at [this](https://github.com/julienschmidt/httprouter/issues/148).

**Comment by tidwall** [comment]
@hiyali thanks for the 411. I’ll reevaluate iris and likely drop it from the benchmarks.

**Comment by tidwall** [comment]
I just dropped iris from the benchmarks.
