### ISSUE TITLE
CPU consuming 100%

### ISSUE THREAD

**Issue by namkazt** [tidwall/evio#61]
I'm not really sure why but after a few hours of running with minimum connection ( around 100 ). CPU usage starts growing up to 100%. here is profile.

```
(pprof) top5 -cum
Showing nodes accounting for 9.86hrs, 79.77% of 12.36hrs total
Dropped 348 nodes (cum <= 0.06hrs)
Showing top 5 nodes out of 23
      flat  flat%   sum%        cum   cum%
         0     0%     0%   12.02hrs 97.25%  github.com/tidwall/evio.loopRun
   0.17hrs  1.40%  1.40%   12.02hrs 97.25%  github.com/tidwall/evio/internal.(*Poll).Wait
   0.08hrs  0.61%  2.01%   11.30hrs 91.41%  syscall.EpollWait
   9.57hrs 77.45% 79.46%   11.22hrs 90.80%  syscall.Syscall6
   0.04hrs  0.31% 79.77%    0.88hrs  7.13%  runtime.entersyscall
```
Graph: 
![2020-01-03 10_19_50-Window](https://user-images.githubusercontent.com/6035916/71706322-b50e6880-2e16-11ea-941b-8531720f2025.png)

Do you have any ideas about why it happens?

**Comment by namkazt** [comment]
prof file in case you need it.
[cpu.zip](https://github.com/tidwall/evio/files/4018082/cpu.zip)

**Comment by namkazt** [comment]
Note: if i add this Tick event. Server immedately raise up to 100% CPU usage 
on `aws EC2 small ubuntu 18`
```
events.Tick = func() (delay time.Duration, action evio.Action) {
   delay = 100 * time.Microsecond
   action = evio.None
   return
}
```

if not add it then after some connection. it starts raising up.

**Comment by tidwall** [comment]
Maybe the 100 microsecond delay is too much for that instance size. Do you need the system to tick 10k times per second?

**Comment by namkazt** [comment]
If I'm not set this then in windows version some message is freeze when calling Connection.Wake(). I'm not really sure why but enable Tick event avoid that. But in Ubuntu even not set Tick event it still raise up to 100% use after sometime.

**Comment by tidwall** [comment]
I just pushed a fix. Thanks for your help.
