### ISSUE TITLE
numLoops > 1 will make udp server slower

### ISSUE THREAD

**Issue by tianlin** [tidwall/evio#73]
Hi:
   I found when set numLoops > 1, udp server with evio will be slower than numLoops = 1. Use profile, I found there is too much  syscall in  loopUDPRead(s, l, i, fd).  
   I add a debug code 	fmt.Println("-- loop udp read --", l.idx) before loopUDPRead, then send just one udp msg to it, there are numLoops's print in stdout. I change the LoadBalance to AtLeastConnections / RoundRobin, there is also more call to loopUDPRead when numLoops > 1.

**Comment by cheng-zhongliang** [comment]
> Hi: I found when set numLoops > 1, udp server with evio will be slower than numLoops = 1. Use profile, I found there is too much syscall in loopUDPRead(s, l, i, fd). I add a debug code fmt.Println("-- loop udp read --", l.idx) before loopUDPRead, then send just one udp msg to it, there are numLoops's print in stdout. I change the LoadBalance to AtLeastConnections / RoundRobin, there is also more call to loopUDPRead when numLoops > 1.

on the linux platform，evio works by epoll,  and the epoll instances num = numLoops. Many epoll instances watch the same udp fd. This will cause thundering herd problems. so you found too much syscall.

**Comment by tianlin** [comment]
> > Hi: I found when set numLoops > 1, udp server with evio will be slower than numLoops = 1. Use profile, I found there is too much syscall in loopUDPRead(s, l, i, fd). I add a debug code fmt.Println("-- loop udp read --", l.idx) before loopUDPRead, then send just one udp msg to it, there are numLoops's print in stdout. I change the LoadBalance to AtLeastConnections / RoundRobin, there is also more call to loopUDPRead when numLoops > 1.
> 
> on the linux platform，evio works by epoll, and the epoll instances num = numLoops. Many epoll instances watch the same udp fd. This will cause thundering herd problems. so you found too much syscall.

thx
