### ISSUE TITLE
Info structure in events.Opened is empty

### ISSUE THREAD

**Issue by themester** [tidwall/evio#8]
Code:
```go
events.Opened = func(id int, info evio.Info) (out []byte, opts evio.Options, action evio.Action) {
    log.Printf("opened: %d: %v\n", id, info.RemoteAddr)
    return
  }
```
Output:
```
opened: 1: <nil>
```

**Comment by tidwall** [comment]
Thanks for reporting. Which OS and Go version are you using?

**Comment by themester** [comment]
I'm sorry, check my pull request. You wrote addr instead of info in RemoteAddr

**Comment by tidwall** [comment]
No worries. 

Is

```go
log.Printf("opened: %d: %v\n", id, info.RemoteAddr)
```

still producing

```
opened: 1: <nil>
```

**Comment by themester** [comment]
```bash
mester > go version
go version go1.9.2 linux/amd64
```
```bash
mester > uname -a
Linux xpad 4.13.11_1 #1 SMP PREEMPT Sat Nov 4 05:10:07 UTC 2017 x86_64 GNU/Linux
```

**Comment by tidwall** [comment]
Thanks for the OS information. 
I wasn't entirely clear from your previous comment, but is the issue `info.RemoteAddr` still producing `<nil>` from the `Opened` event?

**Comment by themester** [comment]
Yes. I check it and it still producing nil value

**Comment by tidwall** [comment]
I'm unable to reproduce. Could you provide detailed steps / code?
